name: ML Pipeline

on:
  push:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - run: pip install mlflow scikit-learn dvc

      - run: dvc pull
        continue-on-error: true

      - run: python train.py
        env:
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}

      - uses: actions/upload-artifact@v4
        with:
          name: model-info
          path: model_info.txt

  deploy:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - run: pip install mlflow

      - uses: actions/download-artifact@v4
        with:
          name: model-info

      - run: python check_threshold.py
        env:
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}

      - run: echo "Building Docker image for Run ID $(cat model_info.txt)"